feat: Add selection parsing

diff --git a/hyprcap b/hyprcap
--- a/hyprcap
+++ b/hyprcap
@@ -50,7 +50,7 @@ Selection:
 
 
 Selection options:
-! -s, --select <selection>      Alternative way to specify the selection.
+  -s, --select <selection>      Alternative way to specify the selection.
 
 Saving options:
 ! -o, --output-dir <dir>        Directory in which to save captures.
@@ -371,8 +371,7 @@ function args() {
     while true; do
         case "$1" in
             -s | --select)
-                # TODO: Call parsing function here
-                NYI && exit 1 # TODO: Remove when implemented
+                local selection="$2" # Parsing is done later
                 shift;;
 
             -o | --output-dir)
@@ -452,6 +451,20 @@ function args() {
         exit 1
     fi
     COMMAND=$(parse_command "$1")
+
+    # -- Selection --
+    # If a selection was not specified already and there is another argument,
+    # use it as the selection
+    [ -z "$selection" -a -n "$2" ] && selection="$2"
+
+    # If no selection is done yet, fail
+    # TODO: Remove this when dmenu-based selection is implemented
+    if [ -z "$selection" ]; then
+        Print -E "Fatal: No selection specified. Use --help for help.\n"
+        exit 1
+    fi
+
+    parse_selection "$selection" # Errors and exit if selection is invalid
 }
 
 function parse_command() {
@@ -469,30 +482,34 @@ function parse_command() {
     esac
 }
 
-# function parse_mode() {
-#     local mode="${1}"
+function parse_selection() {
+    local selection="$1"
 
-#     case "$1" in
-#         active)
-#             CURRENT=1
-#             ;;
-#         window | region | output)
-#             OPTION="$1"
-#             ;;
-#         Window:*)
-#             OPTION=window
-#             SELECTED_WINDOW="$(echo "$1" | cut -f2)"
-#             ;;
-#         Monitor:*)
-#             OPTION=output
-#             SELECTED_MONITOR="$(echo "$1" | cut -f2)"
-#             ;;
-#         *)
-#             hyprctl monitors -j | jq -re '.[] | select(.name == "'$(echo "$1")'")' &>/dev/null
-#             SELECTED_MONITOR="$1"
-#             ;;
-#     esac
-# }
+    case "$selection" in
+        region*)
+            ;; # Region is excluded with these options, must be used alone
+        *:active)
+            ACTIVE=1
+            selection="${1%:active}"
+            ;;
+        *:* | *:*)
+            SELECTION_OPTION="${1#*:}"
+            selection="${1%%:$SELECTION_OPTION}"
+            ;;
+        *)
+            selection="$1"
+            ;;
+    esac
+
+    case "$selection" in
+        window | region | monitor)
+            SELECTION="$selection"
+            ;;
+        *)
+            Print -E "Fatal: Unknown selection '$1'\n"
+            exit 1;;
+    esac
+}
 
 # function prompt_options() {
 #     visible_windows=$(list_geometry)
@@ -529,7 +546,7 @@ function parse_command() {
 # ---- Options and defaults ----
 
 # Selection
-# SELECTION=
+SELECTION=
 
 # Saving
 # SAVE=0 # not implemented yet
@@ -555,6 +572,7 @@ args $0 "$@"
 
 Print -1 "Running HyprCap version $VERSION\n"
 Print -1 "Command selected: $COMMAND\n"
+Print -1 "Selection: $SELECTION\n"
 
 # startup
 
